//
//  AddTrainingEventSheet.swift
//  NeuronestiOS
//
//  Created by HashtagPro on 1/2/26.
//


import SwiftUI

struct AddTrainingEventSheet: View {
    var onSave: (String, Date, Int, String?) -> Void

    @State private var title = "Neuronest Training"
    @State private var start = Calendar.current.date(byAdding: .day, value: 1, to: Date()) ?? Date()
    @State private var minutes = 20
    @State private var notes = "Cognitive training session generated by Neuronest."

    var body: some View {
        NavigationStack {
            Form {
                Section("Details") {
                    TextField("Title", text: $title)
                    DatePicker("Start", selection: $start, displayedComponents: [.date, .hourAndMinute])
                    Stepper("Duration: \(minutes) min", value: $minutes, in: 5...180, step: 5)
                    TextField("Notes", text: $notes, axis: .vertical)
                        .lineLimit(3...6)
                }
            }
            .navigationTitle("Add Session")
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button("Cancel") {
                        // sheet 닫기는 부모에서 제어
                        // 부모가 isPresented 끄는 방식이라 여기선 비워둬도 OK
                    }
                }
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Save") {
                        onSave(title, start, minutes, notes)
                    }
                }
            }
        }
    }
}